import { createContext, useContext, useEffect, useMemo, type ReactNode } from "react";

import type { AppLocale } from "../settings/display/service";

export type ResolvedLocale = Exclude<AppLocale, "system">;
export type TranslationValues = Record<string, string | number>;

const english = {
  "language.title": "Language",
  "language.description": "Choose the language Cookbench uses across its Bars and Settings.",
  "language.system": "Follow system",
  "language.en": "English",
  "language.zh-CN": "Simplified Chinese",
  "language.ja": "Japanese",
  "language.ko": "Korean",
  "settings.title": "Settings",
  "settings.general": "General",
  "settings.archive": "Archive",
  "common.save": "Save",
  "common.close": "Close",
  "common.clear": "Clear",
  "common.delete": "Delete",
  "common.pin": "Pin",
  "common.unpin": "Unpin",
  "common.detach": "Detach",
  "common.restore": "Restore",
  "common.add": "Add",
  "common.remove": "Remove",
  "common.enable": "Enable",
  "common.disable": "Disable",
  "common.preview": "Preview",
  "common.install": "Install",
  "common.repair": "Repair",
  "common.uninstall": "Uninstall",
  "common.enabled": "Enabled",
  "common.states": "States",
  "common.notReported": "Not reported",
  "common.currentSession": "Current session",
  "state.starting": "Starting", "state.planning": "Planning", "state.cooking": "Cooking", "state.needsHuman": "Needs human", "state.cooked": "Cooked", "state.failed": "Failed", "state.disconnected": "Disconnected", "state.offline": "Offline",
  "bar.global": "Cookbench global bar with {count} stoves", "bar.openSettings": "Open Cookbench settings", "bar.settings": "Settings", "bar.stoves": "Stoves", "bar.harnessStoves": "{name} stoves", "bar.detached": "Detached Stove bar for {name}",
  "stove.closeDetached": "Close detached Stove", "stove.clear": "Clear {name} Stove", "stove.delete": "Delete {name} Stove", "stove.detach": "Detach {name} Stove", "stove.pin": "Pin {name} Stove", "stove.unpin": "Unpin {name} Stove", "stove.complete": "{state}, {percentage}% complete", "stove.session": "Session",
  "host.remote": "Remote", "host.local": "Local", "host.remoteLabel": "Remote host: {host}", "host.localLabel": "Local host: {host}",
  "tooltip.harness": "Harness", "tooltip.host": "Host", "tooltip.project": "Project", "tooltip.session": "Session", "tooltip.state": "State", "tooltip.activity": "Activity", "tooltip.progress": "Progress", "tooltip.elapsed": "Elapsed", "tooltip.next": "Next", "tooltip.waiting": "Waiting for source activity", "tooltip.noProgress": "No structured progress", "tooltip.noNext": "No next action reported", "tooltip.remote": "Remote: {host}", "tooltip.local": "Local: {host}",
  "locator.opening": "Opening the matching Codex task.", "locator.fallback": "Cookbench could not open the original session. It has kept the Stove visible here.", "locator.fallbackWithId": "Cookbench could not open the original session. It has kept the Stove visible here; use this session ID in your original tool:",
  "display.title": "Display", "display.global": "Global Bar", "display.globalDescription": "Shows every Stove in one place.", "display.showGlobal": "Show global Bar", "display.hover": "Show details on hover", "display.placement": "Placement", "display.mode": "Bar mode", "display.modeFull": "Full", "display.modeMinimal": "Minimal", "display.macStatus": "macOS status bar", "display.macStatusDescription": "Show the Stoves that need attention in the menu bar.", "display.macStatusCount": "Visible Stoves", "display.macStatusOff": "0 hides the status item.", "display.topLeft": "Top left", "display.topCenter": "Top center", "display.topRight": "Top right", "display.bottomLeft": "Bottom left", "display.bottomCenter": "Bottom center", "display.bottomRight": "Bottom right", "display.desktop": "Desktop behavior", "display.desktopDescription": "Keep Cookbench available from the system tray.", "display.login": "Launch Cookbench at login", "display.independent": "Independent Bars", "display.independentDescription": "Stay visible even when the global Bar is hidden.", "display.closeIndependent": "Close independent Bar {id}", "display.empty": "No independent Bars are open.", "display.unavailable": "Display settings are unavailable.", "display.loginUnavailable": "Launch at login is unavailable.", "display.saveFailed": "Display settings could not be saved.", "display.closeFailed": "Independent Bar could not be closed.", "display.loginFailed": "Launch at login could not be changed.",
  "archive.expired": "Expired after 2 days", "archive.deleted": "Deleted manually", "archive.restored": "Session restored.", "archive.restoreFailed": "Session could not be restored.", "archive.sourceMissing": "The native session source is no longer available.", "archive.loading": "Loading archived sessions.", "archive.unavailable": "Archived sessions are unavailable.", "archive.empty": "No archived sessions.", "archive.list": "Archived sessions",
  "sources.title": "Local Sources", "sources.description": "Read-only session discovery on this computer.", "sources.list": "Local source status", "sources.unavailable": "Local source status is unavailable.", "sources.healthy": "Watching", "sources.degraded": "Needs attention", "sources.unavailableStatus": "Unavailable", "sources.full": "Full", "sources.standard": "Standard", "sources.experimental": "Experimental", "sources.nativeSessions": "Native sessions", "sources.structuredHook": "Structured hook", "sources.presenceOnly": "Presence only",
  "hooks.title": "Hook Health", "hooks.description": "Optional lifecycle signals. Native session files remain authoritative.", "hooks.list": "Hook health", "hooks.unavailable": "Hook status is unavailable.", "hooks.preview": "Preview only. No harness configuration was changed.", "hooks.updated": "Hook configuration updated.", "hooks.matches": "Hook configuration already matches this action.", "hooks.failed": "Cookbench could not update this hook safely.", "hooks.previewLabel": "Hook configuration preview", "hooks.detected": "Native monitoring", "hooks.notInstalled": "Not installed", "hooks.healthy": "Healthy", "hooks.outdated": "Outdated", "hooks.conflicted": "Configuration conflict", "hooks.unwritable": "Cannot write", "hooks.noRecentEvents": "No recent events", "hooks.automatic": "Automatic", "hooks.manual": "Manual setup", "hooks.presenceOnly": "Presence only",
  "remote.title": "SSH Sources", "remote.alias": "SSH alias", "remote.bridge": "Temporary bridge over SSH stdio", "remote.binary": "Compatible bridge binary (optional)", "remote.packaged": "Packaged binary", "remote.roots": "Session roots", "remote.automatic": "Automatic when empty", "remote.autoRoots": "Automatic supported Harness roots", "remote.stdio": "Temporary stdio bridge", "remote.readOnly": "Zero-install read-only", "remote.unavailable": "SSH sources are unavailable.", "remote.saved": "SSH source saved.", "remote.saveFailed": "SSH source could not be saved.", "remote.updateFailed": "SSH source could not be updated.", "remote.removed": "SSH source removed.", "remote.removeFailed": "SSH source could not be removed.",
  "notifications.local": "Local alerts", "notifications.title": "Notifications", "notifications.sound": "Sound", "notifications.system": "System notification", "notifications.flash": "Flash Stove", "notifications.attention": "Request attention", "notifications.test": "Test", "notifications.template": "Message template", "notifications.botToken": "Bot token", "notifications.webhook": "Webhook URL", "notifications.chatId": "Chat ID", "notifications.stored": "Stored in system credentials", "notifications.notConfigured": "Not configured", "notifications.sessionAppeared": "Session Appeared", "notifications.cookingStarted": "Cooking Started", "notifications.phaseChanged": "Phase Changed", "notifications.needsHuman": "Needs Human", "notifications.progressMilestone": "Progress Milestone", "notifications.cooked": "Cooked", "notifications.failed": "Failed", "notifications.disconnected": "Disconnected", "notifications.connectionRestored": "Connection Restored", "notifications.stoveCleared": "Stove Cleared",
  "notifications.settingsUnavailable": "Notification settings are unavailable.", "notifications.localUnavailable": "Local alert settings are unavailable.", "notifications.saved": "{name} saved.", "notifications.saveFailed": "{name} could not be saved.", "notifications.testSent": "{name} test sent.", "notifications.testFailed": "{name} test failed.", "notifications.localSaved": "Local alerts saved.", "notifications.localSaveFailed": "Local alerts could not be saved.", "notifications.permission": "{name} needs system notification permission.", "notifications.channelUnavailable": "{name} is unavailable on this system.", "notifications.localTestFailed": "Local alert test failed.",
  "sources.sessionCount": "{count} session", "sources.sessionCountPlural": "{count} sessions", "sources.issueCount": "{count} parsing issue", "sources.issueCountPlural": "{count} parsing issues", "hooks.actions": "{name} hook actions",
} as const;

const zh: Record<keyof typeof english, string> = {
  ...english,
  "language.title":"语言", "language.description":"选择 Cookbench 在 Bar 和设置中使用的语言。", "language.system":"跟随系统", "language.en":"English", "language.zh-CN":"简体中文", "language.ja":"日语", "language.ko":"韩语", "settings.title":"设置", "settings.general":"通用", "settings.archive":"归档", "common.save":"保存", "common.close":"关闭", "common.clear":"清除", "common.delete":"删除", "common.pin":"固定", "common.unpin":"取消固定", "common.detach":"独立显示", "common.restore":"恢复", "common.add":"添加", "common.remove":"移除", "common.enable":"启用", "common.disable":"停用", "common.preview":"预览", "common.install":"安装", "common.repair":"修复", "common.uninstall":"卸载", "common.enabled":"已启用", "common.states":"状态", "common.notReported":"未报告", "common.currentSession":"当前会话",
  "state.starting":"启动中", "state.planning":"规划中", "state.cooking":"进行中", "state.needsHuman":"需要人工处理", "state.cooked":"已完成", "state.failed":"失败", "state.disconnected":"已断开", "state.offline":"离线", "bar.global":"Cookbench 全局 Bar，共 {count} 个 Stove", "bar.openSettings":"打开 Cookbench 设置", "bar.settings":"设置", "bar.stoves":"Stove", "bar.harnessStoves":"{name} Stove", "bar.detached":"{name} 的独立 Stove Bar", "stove.closeDetached":"关闭独立 Stove", "stove.clear":"清除 {name} Stove", "stove.delete":"删除 {name} Stove", "stove.detach":"独立显示 {name} Stove", "stove.pin":"固定 {name} Stove", "stove.unpin":"取消固定 {name} Stove", "stove.complete":"{state}，完成 {percentage}%", "stove.session":"会话",
  "host.remote":"远程", "host.local":"本地", "host.remoteLabel":"远程主机：{host}", "host.localLabel":"本地主机：{host}", "tooltip.harness":"Harness", "tooltip.host":"主机", "tooltip.project":"项目", "tooltip.session":"会话", "tooltip.state":"状态", "tooltip.activity":"活动", "tooltip.progress":"进度", "tooltip.elapsed":"已用时间", "tooltip.next":"下一步", "tooltip.waiting":"等待来源活动", "tooltip.noProgress":"没有结构化进度", "tooltip.noNext":"未报告下一步操作", "tooltip.remote":"远程：{host}", "tooltip.local":"本地：{host}", "locator.opening":"正在打开对应的 Codex 任务。", "locator.fallback":"Cookbench 无法打开原始会话，已在此保留 Stove。", "locator.fallbackWithId":"Cookbench 无法打开原始会话，已在此保留 Stove；请在原工具中使用此会话 ID：",
  "display.title":"显示", "display.global":"全局 Bar", "display.globalDescription":"在一个位置显示所有 Stove。", "display.showGlobal":"显示全局 Bar", "display.hover":"悬浮时显示详情", "display.placement":"位置", "display.mode":"Bar 模式", "display.modeFull":"完整", "display.modeMinimal":"极简", "display.macStatus":"macOS 状态栏", "display.macStatusDescription":"在菜单栏显示需要关注的 Stove。", "display.macStatusCount":"显示 Stove 数量", "display.macStatusOff":"0 时隐藏状态栏项目。", "display.topLeft":"左上", "display.topCenter":"顶部居中", "display.topRight":"右上", "display.bottomLeft":"左下", "display.bottomCenter":"底部居中", "display.bottomRight":"右下", "display.desktop":"桌面行为", "display.desktopDescription":"让 Cookbench 可从系统托盘打开。", "display.login":"登录时启动 Cookbench", "display.independent":"独立 Bar", "display.independentDescription":"即使全局 Bar 隐藏，也继续显示。", "display.closeIndependent":"关闭独立 Bar {id}", "display.empty":"没有打开的独立 Bar。", "display.unavailable":"显示设置不可用。", "display.loginUnavailable":"登录启动设置不可用。", "display.saveFailed":"无法保存显示设置。", "display.closeFailed":"无法关闭独立 Bar。", "display.loginFailed":"无法更改登录启动设置。",
  "archive.expired":"已在 2 天后过期", "archive.deleted":"已手动删除", "archive.restored":"会话已恢复。", "archive.restoreFailed":"无法恢复会话。", "archive.sourceMissing":"原生会话来源已不可用。", "archive.loading":"正在加载归档会话。", "archive.unavailable":"归档会话不可用。", "archive.empty":"没有归档会话。", "archive.list":"归档会话",
  "sources.title":"本地来源", "sources.description":"只读发现此电脑上的会话。", "sources.list":"本地来源状态", "sources.unavailable":"本地来源状态不可用。", "sources.healthy":"监控中", "sources.degraded":"需要注意", "sources.unavailableStatus":"不可用", "sources.full":"完整", "sources.standard":"标准", "sources.experimental":"实验性", "sources.nativeSessions":"原生会话", "sources.structuredHook":"结构化 Hook", "sources.presenceOnly":"仅存在检测",
  "hooks.title":"Hook 健康状态", "hooks.description":"可选的生命周期信号。原生会话文件仍是事实来源。", "hooks.list":"Hook 健康状态", "hooks.unavailable":"Hook 状态不可用。", "hooks.preview":"仅预览，未更改 Harness 配置。", "hooks.updated":"Hook 配置已更新。", "hooks.matches":"Hook 配置已与此操作一致。", "hooks.failed":"Cookbench 无法安全地更新此 Hook。", "hooks.previewLabel":"Hook 配置预览", "hooks.detected":"原生监控", "hooks.notInstalled":"未安装", "hooks.healthy":"健康", "hooks.outdated":"已过期", "hooks.conflicted":"配置冲突", "hooks.unwritable":"无法写入", "hooks.noRecentEvents":"没有近期事件", "hooks.automatic":"自动", "hooks.manual":"手动设置", "hooks.presenceOnly":"仅存在检测",
  "remote.title":"SSH 来源", "remote.alias":"SSH 别名", "remote.bridge":"通过 SSH stdio 的临时 bridge", "remote.binary":"兼容的 bridge 二进制文件（可选）", "remote.packaged":"随附二进制文件", "remote.roots":"会话根目录", "remote.automatic":"留空时自动扫描", "remote.autoRoots":"自动识别支持的 Harness 根目录", "remote.stdio":"临时 stdio bridge", "remote.readOnly":"零安装只读", "remote.unavailable":"SSH 来源不可用。", "remote.saved":"SSH 来源已保存。", "remote.saveFailed":"无法保存 SSH 来源。", "remote.updateFailed":"无法更新 SSH 来源。", "remote.removed":"SSH 来源已移除。", "remote.removeFailed":"无法移除 SSH 来源。",
  "notifications.local":"本地提醒", "notifications.title":"通知", "notifications.sound":"声音", "notifications.system":"系统通知", "notifications.flash":"闪烁 Stove", "notifications.attention":"请求注意", "notifications.test":"测试", "notifications.template":"消息模板", "notifications.botToken":"Bot token", "notifications.webhook":"Webhook URL", "notifications.chatId":"Chat ID", "notifications.stored":"已存储在系统凭据中", "notifications.notConfigured":"未配置", "notifications.sessionAppeared":"会话出现", "notifications.cookingStarted":"开始进行", "notifications.phaseChanged":"阶段已变更", "notifications.needsHuman":"需要人工处理", "notifications.progressMilestone":"进度里程碑", "notifications.cooked":"已完成", "notifications.failed":"失败", "notifications.disconnected":"已断开", "notifications.connectionRestored":"连接已恢复", "notifications.stoveCleared":"Stove 已清除",
  "notifications.settingsUnavailable":"通知设置不可用。", "notifications.localUnavailable":"本地提醒设置不可用。", "notifications.saved":"{name} 已保存。", "notifications.saveFailed":"无法保存 {name}。", "notifications.testSent":"已发送 {name} 测试。", "notifications.testFailed":"{name} 测试失败。", "notifications.localSaved":"本地提醒已保存。", "notifications.localSaveFailed":"无法保存本地提醒。", "notifications.permission":"{name} 需要系统通知权限。", "notifications.channelUnavailable":"此系统不支持 {name}。", "notifications.localTestFailed":"本地提醒测试失败。", "sources.sessionCount":"{count} 个会话", "sources.sessionCountPlural":"{count} 个会话", "sources.issueCount":"{count} 个解析问题", "sources.issueCountPlural":"{count} 个解析问题", "hooks.actions":"{name} Hook 操作",
};

// Compact translations keep ordinary chrome local while harness names and diagnostics stay verbatim.
const ja: Record<keyof typeof english, string> = { ...english, "language.title":"言語", "language.description":"Cookbench の Bar と設定で使う言語を選択します。", "language.system":"システムに従う", "language.zh-CN":"簡体字中国語", "language.ja":"日本語", "language.ko":"韓国語", "settings.title":"設定", "settings.general":"一般", "settings.archive":"アーカイブ", "common.save":"保存", "common.close":"閉じる", "common.clear":"クリア", "common.delete":"削除", "common.pin":"固定", "common.unpin":"固定解除", "common.detach":"分離", "common.restore":"復元", "common.add":"追加", "common.remove":"削除", "common.enable":"有効化", "common.disable":"無効化", "common.preview":"プレビュー", "common.install":"インストール", "common.repair":"修復", "common.uninstall":"アンインストール", "common.enabled":"有効", "common.states":"状態", "common.notReported":"未報告", "common.currentSession":"現在のセッション", "state.starting":"開始中", "state.planning":"計画中", "state.cooking":"実行中", "state.needsHuman":"人の対応が必要", "state.cooked":"完了", "state.failed":"失敗", "state.disconnected":"切断", "state.offline":"オフライン", "bar.openSettings":"Cookbench 設定を開く", "bar.settings":"設定", "bar.stoves":"Stove", "host.remote":"リモート", "host.local":"ローカル", "display.title":"表示", "display.global":"グローバル Bar", "display.globalDescription":"すべての Stove を一か所に表示します。", "display.showGlobal":"グローバル Bar を表示", "display.hover":"ホバーで詳細を表示", "display.placement":"配置", "display.topLeft":"左上", "display.topCenter":"上中央", "display.topRight":"右上", "display.bottomLeft":"左下", "display.bottomCenter":"下中央", "display.bottomRight":"右下", "display.desktop":"デスクトップ動作", "display.login":"ログイン時に Cookbench を起動", "display.independent":"独立した Bar", "display.empty":"独立した Bar は開いていません。" };
const ko: Record<keyof typeof english, string> = { ...english, "language.title":"언어", "language.description":"Cookbench의 Bar와 설정에서 사용할 언어를 선택합니다.", "language.system":"시스템 설정", "language.zh-CN":"중국어 간체", "language.ja":"일본어", "language.ko":"한국어", "settings.title":"설정", "settings.general":"일반", "settings.archive":"보관함", "common.save":"저장", "common.close":"닫기", "common.clear":"지우기", "common.delete":"삭제", "common.pin":"고정", "common.unpin":"고정 해제", "common.detach":"분리", "common.restore":"복원", "common.add":"추가", "common.remove":"제거", "common.enable":"사용", "common.disable":"사용 안 함", "common.preview":"미리보기", "common.install":"설치", "common.repair":"복구", "common.uninstall":"제거", "common.enabled":"사용", "common.states":"상태", "common.notReported":"보고되지 않음", "common.currentSession":"현재 세션", "state.starting":"시작 중", "state.planning":"계획 중", "state.cooking":"진행 중", "state.needsHuman":"사용자 확인 필요", "state.cooked":"완료", "state.failed":"실패", "state.disconnected":"연결 끊김", "state.offline":"오프라인", "bar.openSettings":"Cookbench 설정 열기", "bar.settings":"설정", "bar.stoves":"Stove", "host.remote":"원격", "host.local":"로컬", "display.title":"표시", "display.global":"전역 Bar", "display.globalDescription":"모든 Stove를 한곳에 표시합니다.", "display.showGlobal":"전역 Bar 표시", "display.hover":"마우스를 올리면 세부 정보 표시", "display.placement":"위치", "display.topLeft":"왼쪽 위", "display.topCenter":"위 가운데", "display.topRight":"오른쪽 위", "display.bottomLeft":"왼쪽 아래", "display.bottomCenter":"아래 가운데", "display.bottomRight":"오른쪽 아래", "display.desktop":"데스크톱 동작", "display.login":"로그인할 때 Cookbench 시작", "display.independent":"독립 Bar", "display.empty":"열려 있는 독립 Bar가 없습니다." };

const jaComplete: Record<keyof typeof english, string> = {
  ...ja,
  "bar.global":"Cookbench グローバル Bar、{count} 個の Stove", "bar.harnessStoves":"{name} の Stove", "bar.detached":"{name} の独立 Stove Bar",
  "stove.closeDetached":"独立 Stove を閉じる", "stove.clear":"{name} Stove をクリア", "stove.delete":"{name} Stove を削除", "stove.detach":"{name} Stove を分離", "stove.pin":"{name} Stove を固定", "stove.unpin":"{name} Stove の固定を解除", "stove.complete":"{state}、{percentage}% 完了", "stove.session":"セッション",
  "host.remoteLabel":"リモートホスト: {host}", "host.localLabel":"ローカルホスト: {host}",
  "tooltip.harness":"Harness", "tooltip.host":"ホスト", "tooltip.project":"プロジェクト", "tooltip.session":"セッション", "tooltip.state":"状態", "tooltip.activity":"アクティビティ", "tooltip.progress":"進捗", "tooltip.elapsed":"経過時間", "tooltip.next":"次の操作", "tooltip.waiting":"ソースのアクティビティを待機中", "tooltip.noProgress":"構造化された進捗はありません", "tooltip.noNext":"次の操作は報告されていません", "tooltip.remote":"リモート: {host}", "tooltip.local":"ローカル: {host}",
  "locator.opening":"対応する Codex タスクを開いています。", "locator.fallback":"Cookbench は元のセッションを開けませんでした。Stove はここに表示したままです。", "locator.fallbackWithId":"Cookbench は元のセッションを開けませんでした。Stove はここに表示したままです。元のツールでこのセッション ID を使用してください:",
  "display.mode":"Bar モード", "display.modeFull":"フル", "display.modeMinimal":"最小", "display.macStatus":"macOS ステータスバー", "display.macStatusDescription":"メニューバーに注意が必要な Stove を表示します。", "display.macStatusCount":"表示する Stove", "display.macStatusOff":"0 でステータス項目を非表示にします。", "display.desktopDescription":"システムトレイから Cookbench を利用できるようにします。", "display.independentDescription":"グローバル Bar を隠しても表示を維持します。", "display.closeIndependent":"独立 Bar {id} を閉じる", "display.unavailable":"表示設定を利用できません。", "display.loginUnavailable":"ログイン時起動の設定を利用できません。", "display.saveFailed":"表示設定を保存できませんでした。", "display.closeFailed":"独立 Bar を閉じられませんでした。", "display.loginFailed":"ログイン時起動を変更できませんでした。",
  "archive.expired":"2 日後に期限切れ", "archive.deleted":"手動で削除", "archive.restored":"セッションを復元しました。", "archive.restoreFailed":"セッションを復元できませんでした。", "archive.sourceMissing":"ネイティブセッションのソースは利用できなくなりました。", "archive.loading":"アーカイブ済みセッションを読み込んでいます。", "archive.unavailable":"アーカイブ済みセッションを利用できません。", "archive.empty":"アーカイブ済みセッションはありません。", "archive.list":"アーカイブ済みセッション",
  "sources.title":"ローカルソース", "sources.description":"このコンピューター上のセッションを読み取り専用で検出します。", "sources.list":"ローカルソースの状態", "sources.unavailable":"ローカルソースの状態を利用できません。", "sources.healthy":"監視中", "sources.degraded":"注意が必要", "sources.unavailableStatus":"利用不可", "sources.full":"完全", "sources.standard":"標準", "sources.experimental":"実験的", "sources.nativeSessions":"ネイティブセッション", "sources.structuredHook":"構造化 Hook", "sources.presenceOnly":"存在確認のみ",
  "hooks.title":"Hook の状態", "hooks.description":"任意のライフサイクルシグナルです。ネイティブセッションファイルが正確な情報源です。", "hooks.list":"Hook の状態", "hooks.unavailable":"Hook の状態を利用できません。", "hooks.preview":"プレビューのみです。Harness の設定は変更されていません。", "hooks.updated":"Hook の設定を更新しました。", "hooks.matches":"Hook の設定はすでにこの操作と一致しています。", "hooks.failed":"Cookbench はこの Hook を安全に更新できませんでした。", "hooks.previewLabel":"Hook 設定のプレビュー", "hooks.detected":"ネイティブ監視", "hooks.notInstalled":"未インストール", "hooks.healthy":"正常", "hooks.outdated":"古い状態", "hooks.conflicted":"設定の競合", "hooks.unwritable":"書き込み不可", "hooks.noRecentEvents":"最近のイベントなし", "hooks.automatic":"自動", "hooks.manual":"手動設定", "hooks.presenceOnly":"存在確認のみ",
  "remote.title":"SSH ソース", "remote.alias":"SSH エイリアス", "remote.bridge":"SSH stdio 経由の一時 bridge", "remote.binary":"互換 bridge バイナリ（任意）", "remote.packaged":"同梱バイナリ", "remote.roots":"セッションルート", "remote.automatic":"空欄なら自動", "remote.autoRoots":"対応する Harness ルートを自動検出", "remote.stdio":"一時 stdio bridge", "remote.readOnly":"インストール不要の読み取り専用", "remote.unavailable":"SSH ソースを利用できません。", "remote.saved":"SSH ソースを保存しました。", "remote.saveFailed":"SSH ソースを保存できませんでした。", "remote.updateFailed":"SSH ソースを更新できませんでした。", "remote.removed":"SSH ソースを削除しました。", "remote.removeFailed":"SSH ソースを削除できませんでした。",
  "notifications.local":"ローカル通知", "notifications.title":"通知", "notifications.sound":"サウンド", "notifications.system":"システム通知", "notifications.flash":"Stove を点滅", "notifications.attention":"注意を要求", "notifications.test":"テスト", "notifications.template":"メッセージテンプレート", "notifications.botToken":"Bot トークン", "notifications.webhook":"Webhook URL", "notifications.chatId":"チャット ID", "notifications.stored":"システム認証情報に保存済み", "notifications.notConfigured":"未設定", "notifications.sessionAppeared":"セッションが出現", "notifications.cookingStarted":"処理を開始", "notifications.phaseChanged":"フェーズが変更", "notifications.needsHuman":"人の対応が必要", "notifications.progressMilestone":"進捗マイルストーン", "notifications.cooked":"完了", "notifications.failed":"失敗", "notifications.disconnected":"切断", "notifications.connectionRestored":"接続を復旧", "notifications.stoveCleared":"Stove をクリア",
  "notifications.settingsUnavailable":"通知設定を利用できません。", "notifications.localUnavailable":"ローカル通知設定を利用できません。", "notifications.saved":"{name} を保存しました。", "notifications.saveFailed":"{name} を保存できませんでした。", "notifications.testSent":"{name} のテストを送信しました。", "notifications.testFailed":"{name} のテストに失敗しました。", "notifications.localSaved":"ローカル通知を保存しました。", "notifications.localSaveFailed":"ローカル通知を保存できませんでした。", "notifications.permission":"{name} にはシステム通知の許可が必要です。", "notifications.channelUnavailable":"このシステムでは {name} を利用できません。", "notifications.localTestFailed":"ローカル通知のテストに失敗しました。", "sources.sessionCount":"{count} セッション", "sources.sessionCountPlural":"{count} セッション", "sources.issueCount":"{count} 件の解析問題", "sources.issueCountPlural":"{count} 件の解析問題", "hooks.actions":"{name} Hook の操作",
};

const koComplete: Record<keyof typeof english, string> = {
  ...ko,
  "bar.global":"Cookbench 전역 Bar, Stove {count}개", "bar.harnessStoves":"{name} Stove", "bar.detached":"{name} 독립 Stove Bar",
  "stove.closeDetached":"독립 Stove 닫기", "stove.clear":"{name} Stove 지우기", "stove.delete":"{name} Stove 삭제", "stove.detach":"{name} Stove 분리", "stove.pin":"{name} Stove 고정", "stove.unpin":"{name} Stove 고정 해제", "stove.complete":"{state}, {percentage}% 완료", "stove.session":"세션",
  "host.remoteLabel":"원격 호스트: {host}", "host.localLabel":"로컬 호스트: {host}",
  "tooltip.harness":"Harness", "tooltip.host":"호스트", "tooltip.project":"프로젝트", "tooltip.session":"세션", "tooltip.state":"상태", "tooltip.activity":"활동", "tooltip.progress":"진행률", "tooltip.elapsed":"경과 시간", "tooltip.next":"다음", "tooltip.waiting":"소스 활동을 기다리는 중", "tooltip.noProgress":"구조화된 진행률 없음", "tooltip.noNext":"다음 작업이 보고되지 않음", "tooltip.remote":"원격: {host}", "tooltip.local":"로컬: {host}",
  "locator.opening":"일치하는 Codex 작업을 여는 중입니다.", "locator.fallback":"Cookbench가 원래 세션을 열 수 없습니다. Stove는 여기에서 계속 표시됩니다.", "locator.fallbackWithId":"Cookbench가 원래 세션을 열 수 없습니다. Stove는 여기에서 계속 표시됩니다. 원래 도구에서 이 세션 ID를 사용하세요:",
  "display.mode":"Bar 모드", "display.modeFull":"전체", "display.modeMinimal":"최소", "display.macStatus":"macOS 상태 막대", "display.macStatusDescription":"메뉴 막대에 주의가 필요한 Stove를 표시합니다.", "display.macStatusCount":"표시할 Stove", "display.macStatusOff":"0이면 상태 항목을 숨깁니다.", "display.desktopDescription":"시스템 트레이에서 Cookbench를 계속 사용할 수 있습니다.", "display.independentDescription":"전역 Bar를 숨겨도 계속 표시됩니다.", "display.closeIndependent":"독립 Bar {id} 닫기", "display.unavailable":"표시 설정을 사용할 수 없습니다.", "display.loginUnavailable":"로그인 시 시작 설정을 사용할 수 없습니다.", "display.saveFailed":"표시 설정을 저장할 수 없습니다.", "display.closeFailed":"독립 Bar를 닫을 수 없습니다.", "display.loginFailed":"로그인 시 시작 설정을 변경할 수 없습니다.",
  "archive.expired":"2일 후 만료", "archive.deleted":"수동으로 삭제됨", "archive.restored":"세션이 복원되었습니다.", "archive.restoreFailed":"세션을 복원할 수 없습니다.", "archive.sourceMissing":"네이티브 세션 소스를 더 이상 사용할 수 없습니다.", "archive.loading":"보관된 세션을 불러오는 중입니다.", "archive.unavailable":"보관된 세션을 사용할 수 없습니다.", "archive.empty":"보관된 세션이 없습니다.", "archive.list":"보관된 세션",
  "sources.title":"로컬 소스", "sources.description":"이 컴퓨터에서 세션을 읽기 전용으로 찾습니다.", "sources.list":"로컬 소스 상태", "sources.unavailable":"로컬 소스 상태를 사용할 수 없습니다.", "sources.healthy":"감시 중", "sources.degraded":"주의 필요", "sources.unavailableStatus":"사용할 수 없음", "sources.full":"전체", "sources.standard":"표준", "sources.experimental":"실험적", "sources.nativeSessions":"네이티브 세션", "sources.structuredHook":"구조화된 Hook", "sources.presenceOnly":"존재 여부만",
  "hooks.title":"Hook 상태", "hooks.description":"선택적 수명 주기 신호입니다. 네이티브 세션 파일이 기준 정보입니다.", "hooks.list":"Hook 상태", "hooks.unavailable":"Hook 상태를 사용할 수 없습니다.", "hooks.preview":"미리보기만 표시됩니다. Harness 구성은 변경되지 않았습니다.", "hooks.updated":"Hook 구성이 업데이트되었습니다.", "hooks.matches":"Hook 구성이 이미 이 작업과 일치합니다.", "hooks.failed":"Cookbench가 이 Hook을 안전하게 업데이트할 수 없습니다.", "hooks.previewLabel":"Hook 구성 미리보기", "hooks.detected":"네이티브 모니터링", "hooks.notInstalled":"설치되지 않음", "hooks.healthy":"정상", "hooks.outdated":"오래됨", "hooks.conflicted":"구성 충돌", "hooks.unwritable":"쓸 수 없음", "hooks.noRecentEvents":"최근 이벤트 없음", "hooks.automatic":"자동", "hooks.manual":"수동 설정", "hooks.presenceOnly":"존재 여부만",
  "remote.title":"SSH 소스", "remote.alias":"SSH 별칭", "remote.bridge":"SSH stdio를 통한 임시 bridge", "remote.binary":"호환 bridge 바이너리(선택 사항)", "remote.packaged":"패키지 바이너리", "remote.roots":"세션 루트", "remote.automatic":"비워 두면 자동", "remote.autoRoots":"지원되는 Harness 루트를 자동 검색", "remote.stdio":"임시 stdio bridge", "remote.readOnly":"설치 없는 읽기 전용", "remote.unavailable":"SSH 소스를 사용할 수 없습니다.", "remote.saved":"SSH 소스가 저장되었습니다.", "remote.saveFailed":"SSH 소스를 저장할 수 없습니다.", "remote.updateFailed":"SSH 소스를 업데이트할 수 없습니다.", "remote.removed":"SSH 소스가 제거되었습니다.", "remote.removeFailed":"SSH 소스를 제거할 수 없습니다.",
  "notifications.local":"로컬 알림", "notifications.title":"알림", "notifications.sound":"소리", "notifications.system":"시스템 알림", "notifications.flash":"Stove 깜박임", "notifications.attention":"주의 요청", "notifications.test":"테스트", "notifications.template":"메시지 템플릿", "notifications.botToken":"Bot 토큰", "notifications.webhook":"Webhook URL", "notifications.chatId":"채팅 ID", "notifications.stored":"시스템 자격 증명에 저장됨", "notifications.notConfigured":"구성되지 않음", "notifications.sessionAppeared":"세션이 나타남", "notifications.cookingStarted":"작업 시작", "notifications.phaseChanged":"단계 변경", "notifications.needsHuman":"사용자 확인 필요", "notifications.progressMilestone":"진행률 이정표", "notifications.cooked":"완료", "notifications.failed":"실패", "notifications.disconnected":"연결 끊김", "notifications.connectionRestored":"연결 복원", "notifications.stoveCleared":"Stove 지워짐",
  "notifications.settingsUnavailable":"알림 설정을 사용할 수 없습니다.", "notifications.localUnavailable":"로컬 알림 설정을 사용할 수 없습니다.", "notifications.saved":"{name}이(가) 저장되었습니다.", "notifications.saveFailed":"{name}을(를) 저장할 수 없습니다.", "notifications.testSent":"{name} 테스트를 보냈습니다.", "notifications.testFailed":"{name} 테스트에 실패했습니다.", "notifications.localSaved":"로컬 알림이 저장되었습니다.", "notifications.localSaveFailed":"로컬 알림을 저장할 수 없습니다.", "notifications.permission":"{name}에는 시스템 알림 권한이 필요합니다.", "notifications.channelUnavailable":"이 시스템에서는 {name}을(를) 사용할 수 없습니다.", "notifications.localTestFailed":"로컬 알림 테스트에 실패했습니다.", "sources.sessionCount":"세션 {count}개", "sources.sessionCountPlural":"세션 {count}개", "sources.issueCount":"구문 분석 문제 {count}개", "sources.issueCountPlural":"구문 분석 문제 {count}개", "hooks.actions":"{name} Hook 작업",
};

const dictionaries: Record<ResolvedLocale, Record<keyof typeof english, string>> = { en: english, "zh-CN": zh, ja: jaComplete, ko: koComplete };

export function resolveLocale(preference: AppLocale, systemLanguage?: string): ResolvedLocale {
  if (preference !== "system") return preference;
  const language = (systemLanguage ?? (typeof navigator === "undefined" ? "en" : navigator.language)).toLowerCase();
  if (language.startsWith("zh")) return "zh-CN";
  if (language.startsWith("ja")) return "ja";
  if (language.startsWith("ko")) return "ko";
  return "en";
}

export type TranslationKey = keyof typeof english;
export type Translate = (key: TranslationKey, values?: TranslationValues) => string;
const defaultTranslate: Translate = (key, values) => interpolate(english[key], values);
const I18nContext = createContext<{ locale: ResolvedLocale; t: Translate }>({ locale: "en", t: defaultTranslate });

function interpolate(template: string, values?: TranslationValues) {
  return template.replace(/\{(\w+)\}/g, (_match, key: string) => String(values?.[key] ?? `{${key}}`));
}

export function I18nProvider({ preference, children }: { preference?: AppLocale; children: ReactNode }) {
  const locale = resolveLocale(preference ?? "system");
  const value = useMemo(() => ({
    locale,
    t: (key: TranslationKey, values?: TranslationValues) => interpolate(
      dictionaries[locale][key] ?? english[key] ?? key,
      values,
    ),
  }), [locale]);
  useEffect(() => {
    document.documentElement.lang = locale;
  }, [locale]);
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>;
}

export function useI18n() { return useContext(I18nContext); }
